### ISSUE TITLE
Paid Memberships Pro – WooCommerce Add On

### ISSUE THREAD

**Issue by kevinlampron916** [strangerstudios/pmpro-woocommerce#97] opened 2018-06-17 06:13 UTC
Just wanted to bring this to everyone's attention who uses "ELEMENTOR"

When the Paid Memberships Pro – WooCommerce Add On is "ACTIVE" you cannot Edit with Elementor.

Everything works fine when the site is running, just when you try to bring the editor up.

In order to edit with Elementor, you have to disable the "Paid Memberships Pro – WooCommerce Add On" plugin in order to use Elementor. Once you are done editing you can reactivate Paid Memberships Pro – WooCommerce Add On.

I hope this helps anyone that has had any issues.

And I hope this will help you developers in coming up with a fix for that.

**Comment by ideadude** [comment] 2018-06-18 14:42
Thanks for the heads up on this. We'll try to figure out what the conflict is so you don't have to juggle the plugin when editing. We're working on a "page builder mega post" that has tips and tricks for getting various page builders to work better with PMPro and our add ons. Some of the updates will work their way into our plugins.

If you notice a related PHP or JavaScript error when trying to edit with the plugin on, it could help us to track this issue down. Thanks.

**Comment by andrewlimaza** [comment] 2022-10-03 08:49
Testing this further, I am unable to replicate the issue Elementor and Paid Memberships Pro - WooCommerce Add On do work as intended.

Please do not hesitate to reach out again if you face any of these issues @kevinlampron916, I will close this issue.

**Closed by andrewlimaza** 2022-10-03 08:49 UTC
Labels: Status: Need to Recreate
