### ISSUE TITLE
Integration doesn't work

### ISSUE THREAD

**Issue by Filipfek** [strangerstudios/pmpro-woocommerce#109] opened 2018-10-30 12:14 UTC
I want to use this option of this plugin:
"Use WooCommerce Products to Buy PMPro Membership Levels"

I've created a product that is buying PMP level. I made a purchase through WooCommerce, but nothing is happening. I did not get access to this level, did I something wrong? Is this option and plugin working at all? I will be grateful for your help :)

**Comment by andrewlimaza** [comment] 2018-10-30 12:41
Hi @Filipfek,

The user's membership level will be assigned once the order has been set to 'completed', if the order has any other status than 'completed' it won't assign the membership level.

If you need further assistance on this, I'd recommend in reaching out to the support team at www.paidmembershipspro.com

**Comment by Filipfek** [comment] 2018-10-30 12:45
Hi :)
Yes, I know, status is 'completed'. But nothing happens. Can you show my an example, video?

**Comment by andrewlimaza** [comment] 2018-10-30 12:53
This should apply the membership level, I noticed you posted inside Multiple Memberships Per Users (MMPU)?

It's possible these two Add Ons might not be working together as MMPU is still in Beta.

**Comment by Filipfek** [comment] 2018-10-30 14:09
Unfortunately, but you're probably right :( It's very bad news. It does not work with MMPU. But even without MMPU, this add-on does not add order to invoices list? I want to sell subscription courses, It seems that currently it is a very difficult task :(

**Comment by andrewlimaza** [comment] 2018-10-30 14:24
When using the WooCommerce Integration, orders won't be added to Paid Memberships Pro orders but only show up in WooCommerce orders.

Something could be interfering with your setup (combination of plugins etc).

If you can test this at it's simplest form with only WooCommerce, Paid Memberships Pro and Paid Memberships Pro WooCommerce Integration to see if it's working as intended.

**Comment by Filipfek** [comment] 2018-10-30 17:46
Yes, I know. I tested it in this way and it actually looks like it works correctly. But I would like to use MMPU :) I did more tests and it turned out that it works with MMPU not bad. Is one very important problem with MMPU, but maybe it can be easily solved? :)

Without MMPU
https://www.screencast.com/t/5L6cdmrLvD
There is an amount (irrelevant) and expiration date (significant). Even if I order the same level again by pmpro-woocommerce, the days will be properly summed up.

With MMPU
https://www.screencast.com/t/sguiL1z5
Unfortunately, there is no expiration date :( Maybe it is possible easily to repair it?

**Comment by andrewlimaza** [comment] 2021-08-25 10:41
I am going to close this issue due to it's age, if you are still experiencing issues please reach out via www.paidmembershipspro.com (this may have been fixed as we've reworked this plugin a bit since this conversation).

Thank you for understanding.

**Closed by andrewlimaza** 2021-08-25 10:41 UTC
