### ISSUE TITLE
WooCommerce Price showing up twice

### ISSUE THREAD

**Issue by ihouzfiles** [strangerstudios/pmpro-woocommerce#152] opened 2021-07-04 10:15 UTC
When this Plugin is installed "Paid Memberships Pro – WooCommerce Add On", it causes the front end of WooCommerce to display the price twice. This is rather annoying and confusing. Is there any way to fix please?
<img width="475" alt="Screenshot 2021-07-04 at 11 15 21" src="https://user-images.githubusercontent.com/40316053/124381216-27386580-dcb9-11eb-8618-4690b547bd2f.png">

**Comment by michaelbeil** [comment] 2021-07-08 14:25
Hey @ihouzfiles,

This has been reported in https://github.com/strangerstudios/pmpro-woocommerce/issues/129 for our development team to consider changing this, however, I do not have an ETA as to when or if this will be developed and included in an update. The code suggestion on the issue should work in the meantime. My apologies for any inconvenience caused by this and thank you for understanding.

**Comment by andrewlimaza** [comment] 2021-08-25 10:12
This has been merged and should be released in upcoming update. Thanks!

**Closed by andrewlimaza** 2021-08-25 10:12 UTC
