### ISSUE TITLE
Membership Discounts not applied

### ISSUE THREAD

**Issue by bekarice** [strangerstudios/pmpro-woocommerce#8] opened 2014-04-24 16:38 UTC
Hey all, may be an issue with membership discounts not being applied for members when viewing catalog, cart, or while checking out.

Steps to replicate (PMPro, WC, WC add-on - all up-to-date on local install):
1. Created membership levels (Basic, Silver, Gold) with associated access and global discount %s.
2. Created products to sell each membership level, linked the appropriate level to each product.
3. Purchased each level with different user accounts logged in.
4. Completed orders for all users.
5. Appropriate membership levels were assigned to each user (checked user profile + sample restricted blog posts to ensure that every user has the right access).
6. Each user is still seeing the basic pricing rather than the global 5%-15% discounts in catalog, product page, cart, and checkout screens. No discounts are applied at any stage for any levels.

**Comment by crashnash86** [comment] 2015-04-05 21:40
Also having the same issue any fix on this, I am running the latest version of wordpress.

**Comment by domialex25** [comment] 2020-02-04 02:07
Having the same issue...

**Comment by andrewlimaza** [comment] 2022-10-03 11:52
I've recently tested this and the issue is resolved. To update this issue, PMPro WooCommerce does not strike through the regular price but rather swap the products price with the discount.

I am going to close this issue and will be on the look out for any issues of this nature with the latest version.

**Closed by andrewlimaza** 2022-10-03 11:52 UTC
Labels: Status: Need to Recreate
