### ISSUE TITLE
{Product} has been removed from your cart because it can no longer be purchased

### ISSUE THREAD

**Issue by chris-dh** [strangerstudios/pmpro-woocommerce#164] opened 2022-02-25 06:16 UTC
Hello,
I am using paid memberships pro to add a membership as product to sell in woocommerce. I installed woocommerce, paid memberships pro and paid memberships pro - woocommerce plugin. When I try to buy the membership product, it also prompt me "has been removed from your cart because it can no longer be purchased" this error and stop me from buying the product.

I did a google search and I can see a lot of people facing the same issue but there was no solution post about how to resolve. Who can help to give me some advice on this? Thanks a lot!

Thanks
Chris

**Comment by andrewlimaza** [comment] 2022-10-03 08:30
Hi @chris-dh 

Thank you for reaching out, for support please reach out to www.paidmembershipspro.com/support.

To briefly touch on this issue, this can be caused by using WooCommerce plugins that bundle products in the cart when you add a product to cart, as we only allow one membership linked product per cart.

I'm going to close this issue as it seems to be site specific and not a PMPro WooCommerce bug.

**Closed by andrewlimaza** 2022-10-03 08:30 UTC
