### ISSUE TITLE
Membership is not canceled in PMPro when a Woo subscription upgrades to a higher membership, then cancels their subscription

### ISSUE THREAD

**Issue by MaryOJob** [strangerstudios/pmpro-woocommerce#162] opened 2022-01-31 11:30 UTC
**Describe the bug**
If a member upgrades to a level with a higher subscription membership from a lower one (for example, the current membership level is $40 and the member upgrades to a level that costs $50), both the initial level and upgraded level are applied in PMPro correctly. 

However, if they go ahead to cancel their subscription, their account goes into pending cancelation and then canceled. Once their membership is canceled, the level in PMPro remains on the level they canceled on. And they still have access to content that should be restricted to that level.

**To Reproduce**
1. Activate and setup 'PMPro WooCommerce, PMPro, WooCommerce Subscriptions'
2. Allow members to be able to upgrade or download in WooCommerce
3. Check out for a level with a lower amount, afterwards, upgrade to a level with a higher amount
4. Check that both initial and upgraded levels are applied correctly in PMPro
5. Cancel your subscription in WooCommerce
6. Go to the WP Edit User profile page once Woo subscription status reads `canceled`
7. See issue

**Screenshots**
<img width="954" alt="Screen Shot 2022-01-31 at 11 29 23" src="https://user-images.githubusercontent.com/25005583/151782038-1ae28394-d347-451f-ae9a-5bc510eecb2c.png">

<img width="848" alt="Screen Shot 2022-01-31 at 11 29 09" src="https://user-images.githubusercontent.com/25005583/151782005-4abcf483-1a0e-424d-8570-3c59872e5db5.png">

![Screen Shot 2022-01-31 at 12 00 07](https://user-images.githubusercontent.com/25005583/151782245-8e7ed9f2-bd4f-4077-9427-d92aafdc2eda.png)

**Expected behavior**
When the WooCommerce subscription is completely canceled, the membership status in PMPro should be set to `None` and level canceled as well.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`WordPress Version 5.9`
`Twenty Twenty Theme Version 1.9`
`WooCommerce Subscriptions Version 3.1.6`
`WooCommerce Version 6.1.1`
`PMPro Version 2.7.2`
`PMPro WooCommerce 1.7.3`
`PHP Version 7.4.27`
```
</details>

**Comment by MaryOJob** [comment] 2022-01-31 11:31
For Moderators Only
Ticket Tag: #391063

**Comment by andrewlimaza** [comment] 2023-01-16 15:38
I've retested this with the latest `dev` branch and it works as intended. Levels are removed when subscriptions are cancelled.

My test had 2 subscriptions linked to different levels, I then cancelled one sub at a time and the relevant level was removed.

**Comment by piotrkunicki** [comment] 2023-01-23 07:21
@andrewlimaza did you test it with the upgrade? This bug occurs only after subscription upgrade (not 2 different subscriptions) (https://woocommerce.com/document/subscriptions/switching-guide/)

**Comment by andrewlimaza** [comment] 2023-01-23 09:57
@piotrkunicki I was able to replicate when using a variation subscription product (upgrading and downgrading the subscription itself). We will continue to investigate this.

**Comment by andrewlimaza** [comment] 2023-01-23 10:03
**Steps to replicate this issue**

1. Create a variable subscription product, with various pricing subscriptions.
2. Link a membership level to this product.
3. Purchase the cheapest subscription (any variation would be able to replicate this issue).
4. Navigate to the WooCommerce account page > subscriptions.
5. View the subscription
6. Select to upgrade the subscription (it should redirect you back to this product page).
7. Choose a different variation product and complete checkout.
8. Cancel the subscription to see the error. The member's level stays active.

If on local environments, be sure to process/approve the order in WooCommerce between each step if it's not marked as "completed".

**Comment by dwanjuki** [comment] 2023-06-08 08:45
I observed that cancelling a _variable subscription product_ order does not cancel the linked membership ever, _even when not upgrading_. 

**To replicate:**
1. Create a variable subscription product.
2. Link a membership to this product.
3. Purchase any variation of this subscription.
4. Navigate to the _WooCommerce > Subscriptions_.
5. Cancel the subscription you just purchased.
6. Observe that the account still has a membership level.

**My environment:** 
WP 6.2.2
PMPro 2.11 
PMPro WooCommerce Add On 1.7.7
WooCommerce 7.7.2 
WooCommerce Subscriptions 5.0.0

Mods: Ticket #498680

**Comment by andrewlimaza** [comment] 2024-03-11 10:23
@dwanjuki adding a note here, the latest `dev` branch now supports Variable Subscription Products and cancellations. Here is the merged PR - https://github.com/strangerstudios/pmpro-woocommerce/pull/199

**Comment by andrewlimaza** [comment] 2024-03-11 12:44
I can confirm that this is now fixed with the `dev` branch! I believe the issue was cancelling with variable subscription products didn't honor this product type and it now does. I will be closing this one out and mark it as resolved.

**Closed by andrewlimaza** 2024-03-11 12:44 UTC
Labels: Difficulty: Medium
